baseURL = 'https://nilephotostudio/'
languageCode = 'es'
title = 'Nicole Fotografía'
defaultContentLanguage = 'es'

[languages]
  [languages.es]
    languageName = 'Español'
    weight = 1
  [languages.gl]
    languageName = 'Galego'
    weight = 2
  [languages.en]
    languageName = 'English'
    weight = 3

[params]
  description = "Portafolio de Nicole Leones"
  whatsapp = "+34633191597"
  instagram = "nile.photo.studio"